import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

export const Material = sequelize.define('Material', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  projectId: { type: DataTypes.INTEGER, allowNull: false },
  materialCode: DataTypes.STRING,
  materialName: { type: DataTypes.STRING, allowNull: false },
  category: DataTypes.STRING,
  specification: DataTypes.TEXT,
  plannedQuantity: { type: DataTypes.FLOAT, defaultValue: 0 },
  receivedQuantity: { type: DataTypes.FLOAT, defaultValue: 0 },
  usedQuantity: { type: DataTypes.FLOAT, defaultValue: 0 },
  remainingStock: { type: DataTypes.FLOAT, defaultValue: 0 },
  minimumStock: { type: DataTypes.FLOAT, defaultValue: 0 },
  reorderLevel: { type: DataTypes.FLOAT, defaultValue: 0 },
  unit: { type: DataTypes.STRING, defaultValue: 'pcs' },
  unitCost: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  estimatedCost: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  actualCost: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  supplier: DataTypes.STRING,
  supplierContact: DataTypes.STRING,
  supplierEmail: DataTypes.STRING,
  purchaseOrderNumber: DataTypes.STRING,
  invoiceNumber: DataTypes.STRING,
  deliveryDate: DataTypes.DATEONLY,
  lastReceivedDate: DataTypes.DATEONLY,
  storageLocation: DataTypes.STRING,
  batchNumber: DataTypes.STRING,
  gradeSpecification: DataTypes.STRING,
  qualityStatus: { type: DataTypes.STRING, defaultValue: 'pending_inspection' },
  inspectedBy: DataTypes.STRING,
  inspectionDate: DataTypes.DATEONLY,
  wastageAllowancePercent: { type: DataTypes.FLOAT, defaultValue: 0 },
  plannedPhase: DataTypes.STRING,
  plannedStartDate: DataTypes.DATEONLY,
  plannedEndDate: DataTypes.DATEONLY,
  priority: { type: DataTypes.ENUM('low', 'normal', 'high', 'critical'), defaultValue: 'normal' },
  bomStatus: { type: DataTypes.ENUM('planned', 'approved', 'revised', 'cancelled'), defaultValue: 'planned' },
  notes: DataTypes.TEXT,
  status: { type: DataTypes.ENUM('pending', 'received', 'used', 'damaged'), defaultValue: 'pending' },
}, {
  timestamps: true,
});
