import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

export const Project = sequelize.define('Project', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  projectName: { type: DataTypes.STRING, allowNull: false },
  projectCode: DataTypes.STRING,
  clientName: DataTypes.STRING,
  clientPhone: DataTypes.STRING,
  clientEmail: DataTypes.STRING,
  contractRef: DataTypes.STRING,
  location: { type: DataTypes.STRING, allowNull: false },
  projectType: { type: DataTypes.STRING, defaultValue: 'Residential' },
  budget: { type: DataTypes.DECIMAL(14, 2), allowNull: false },
  currency: { type: DataTypes.STRING, defaultValue: 'USD' },
  startDate: DataTypes.DATEONLY,
  deadline: { type: DataTypes.DATEONLY, allowNull: false },
  status: { type: DataTypes.ENUM('planning', 'active', 'on_track', 'at_risk', 'delayed', 'completed', 'on_hold'), defaultValue: 'planning' },
  priority: { type: DataTypes.ENUM('low', 'medium', 'normal', 'high', 'critical'), defaultValue: 'normal' },
  progress: { type: DataTypes.FLOAT, defaultValue: 0 },
  siteEngineer: DataTypes.STRING,
  projectManager: DataTypes.STRING,
  totalBuiltArea: DataTypes.FLOAT,
  internalFloorArea: DataTypes.FLOAT,
  frontPorchArea: DataTypes.FLOAT,
  rearVerandaArea: DataTypes.FLOAT,
  floors: DataTypes.INTEGER,
  bedrooms: DataTypes.INTEGER,
  bathrooms: DataTypes.INTEGER,
  roofType: DataTypes.STRING,
  structureType: DataTypes.STRING,
  wallThicknessExternal: DataTypes.FLOAT,
  wallThicknessInternal: DataTypes.FLOAT,
  drawingRef: DataTypes.STRING,
  thumbnailUrl: DataTypes.STRING,
  description: DataTypes.TEXT,
}, {
  timestamps: true,
});
